In [ ]:
import numpy as np 
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sn
from sklearn.model_selection import train_test_split
sn.set_theme(style="darkgrid")
%matplotlib inline

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Heart_Disease_Prediction.csv to Heart_Disease_Prediction.csv


In [ ]:
import io
df = pd.read_csv(io.BytesIO(uploaded['Heart_Disease_Prediction.csv']))

In [ ]:
df

Age  Sex  Chest pain type  ...  Number of vessels fluro  Thallium  Heart Disease
0     70    1                4  ...                        3         3       Presence
1     67    0                3  ...                        0         7        Absence
2     57    1                2  ...                        0         7       Presence
3     64    1                4  ...                        1         7        Absence
4     74    0                2  ...                        1         3        Absence
..   ...  ...              ...  ...                      ...       ...            ...
265   52    1                3  ...                        0         7        Absence
266   44    1                2  ...                        0         7        Absence
267   56    0                2  ...                        0         3        Absence
268   57    1                4  ...                        0         6        Absence
269   67    1                4  ...                        3         3       Presence

[270 rows x 14 columns]

In [ ]:
A = df['Chest pain type']
B = df['EKG results']
C = df['Slope of ST']
D = df['Thallium']
#features = ['Chest pain type','EKG results','Slope of ST','Thallium','Heart Disease']
#cont_df = df[features]
cont_df_A = pd.crosstab(A,df['Heart Disease'])
cont_df_A


Heart Disease    Absence  Presence
Chest pain type                   
1                     15         5
2                     35         7
3                     62        17
4                     38        91

In [ ]:
cont_df_B = pd.crosstab(B,df['Heart Disease'])
cont_df_B

Heart Disease  Absence  Presence
EKG results                     
0                   85        46
1                    1         1
2                   64        73

In [ ]:
cont_df_C = pd.crosstab(C,df['Heart Disease'])
cont_df_C

Heart Disease  Absence  Presence
Slope of ST                     
1                   98        32
2                   44        78
3                    8        10

In [ ]:
cont_df_D = pd.crosstab(D,df['Heart Disease'])
cont_df_D

Heart Disease  Absence  Presence
Thallium                        
3                  119        33
6                    6         8
7                   25        79

In [ ]:
cont_df_E = pd.crosstab(B,D)
cont_df_E

Thallium      3  6   7
EKG results           
0            74  6  51
1             2  0   0
2            76  8  53

In [ ]:
cont_df_F = pd.crosstab(A,D)
cont_df_F

Thallium          3  6   7
Chest pain type           
1                12  2   6
2                33  2   7
3                56  2  21
4                51  8  70

In [ ]:
cont_df_G = pd.crosstab(C,D)
cont_df_G

Thallium      3   6   7
Slope of ST            
1            94   2  34
2            51  11  60
3             7   1  10

In [ ]:
cont_mat_E = cont_df_E.to_numpy()
expected_mat_E = np.outer(cont_mat_E.sum(axis=1)/cont_mat_E.sum(),cont_mat_E.sum(axis=0))
expected_mat_E

array([[73.74814815,  6.79259259, 50.45925926],
       [ 1.12592593,  0.1037037 ,  0.77037037],
       [77.12592593,  7.1037037 , 52.77037037]])

In [ ]:
cont_mat_F = cont_df_F.to_numpy()
expected_mat_F = np.outer(cont_mat_F.sum(axis=1)/cont_mat_F.sum(),cont_mat_F.sum(axis=0))
expected_mat_F

array([[11.25925926,  1.03703704,  7.7037037 ],
       [23.64444444,  2.17777778, 16.17777778],
       [44.47407407,  4.0962963 , 30.42962963],
       [72.62222222,  6.68888889, 49.68888889]])

In [ ]:
cont_mat_G = cont_df_G.to_numpy()
expected_mat_G = np.outer(cont_mat_G.sum(axis=1)/cont_mat_G.sum(),cont_mat_G.sum(axis=0))
expected_mat_G

array([[73.18518519,  6.74074074, 50.07407407],
       [68.68148148,  6.32592593, 46.99259259],
       [10.13333333,  0.93333333,  6.93333333]])

In [ ]:
cont_mat_A = cont_df_A.to_numpy()
cont_mat_B = cont_df_B.to_numpy()
cont_mat_C = cont_df_C.to_numpy()
cont_mat_D = cont_df_D.to_numpy()


In [ ]:
expected_mat_A = np.outer(cont_mat_A.sum(axis=1)/cont_mat_A.sum(),cont_mat_A.sum(axis=0))
expected_mat_A

array([[11.11111111,  8.88888889],
       [23.33333333, 18.66666667],
       [43.88888889, 35.11111111],
       [71.66666667, 57.33333333]])

In [ ]:
expected_mat_B = np.outer(cont_mat_B.sum(axis=1)/cont_mat_B.sum(),cont_mat_B.sum(axis=0))
expected_mat_B

array([[72.77777778, 58.22222222],
       [ 1.11111111,  0.88888889],
       [76.11111111, 60.88888889]])

In [ ]:
expected_mat_C = np.outer(cont_mat_C.sum(axis=1)/cont_mat_C.sum(),cont_mat_C.sum(axis=0))
expected_mat_C

array([[72.22222222, 57.77777778],
       [67.77777778, 54.22222222],
       [10.        ,  8.        ]])

In [ ]:
expected_mat_D = np.outer(cont_mat_D.sum(axis=1)/cont_mat_D.sum(),cont_mat_D.sum(axis=0))
expected_mat_D

array([[84.44444444, 67.55555556],
       [ 7.77777778,  6.22222222],
       [57.77777778, 46.22222222]])

In [ ]:
chi2_values_A = (cont_mat_A - expected_mat_A)**2 / expected_mat_A

In [ ]:
chi2_values_B = (cont_mat_B - expected_mat_B)**2 / expected_mat_B

In [ ]:
chi2_values_C = (cont_mat_C - expected_mat_C)**2 / expected_mat_C

In [ ]:
chi2_values_D = (cont_mat_D - expected_mat_D)**2 / expected_mat_D

In [ ]:
chi2_values_E = (cont_mat_E - expected_mat_E)**2 / expected_mat_E

In [ ]:
chi2_values_F = (cont_mat_F - expected_mat_F)**2 / expected_mat_F

In [ ]:
chi2_values_G = (cont_mat_G - expected_mat_G)**2 / expected_mat_G

In [ ]:
from scipy import stats

In [ ]:
#1 - stats.chi2.cdf(chi2_values_A.sum(),3)
chi2_values_A.sum()

68.58820650574036

In [ ]:
#1 - stats.chi2.cdf(chi2_values_B.sum(),2)
chi2_values_B.sum()

8.979451997548338

In [ ]:
#1 - stats.chi2.cdf(chi2_values_C.sum(),2)
chi2_values_C.sum()

40.370390920554854

In [ ]:
#1 - stats.chi2.cdf(chi2_values_D.sum(),2) #
chi2_values_D.sum()

74.56934644303065

In [ ]:
chi2_values_E.sum()#אקג ותליום

1.7822945706435984

In [ ]:
chi2_values_F.sum()

32.221727584723126

In [ ]:
chi2_values_G.sum()

28.34997833851289

In [ ]:
import scipy.stats as stats
#קשר בין אקג לst depression
fvalue1, pvalue1 = stats.f_oneway(df['ST depression'],df['EKG results'])
print(fvalue1, pvalue1)

0.09029342341640771 0.7639205385079485


In [ ]:
# why we removed FBS - לא טוב זה שני משתנים בינריים
#fvalue2, pvalue2 = stats.f_oneway(df['FBS over 120'],df['Exercise angina'])
#print(fvalue2, pvalue2)

25.51934094590856 6.008516197753887e-07


In [ ]:
# why we removed ST depression
fvalue3, pvalue3 = stats.f_oneway(df['ST depression'],df['Thallium'])
print(fvalue3, pvalue3)

706.9746135104019 4.3739554701943285e-100


In [ ]:

fvalue4, pvalue4 = stats.f_oneway(df['ST depression'],df['Slope of ST'])
print(fvalue4, pvalue4)

45.78753964375341 3.4514420697121187e-11


In [ ]:

fvalue5,pvalue5 = stats.f_oneway(df['Number of vessels fluro'],df['Thallium'])
print(fvalue5, pvalue5)

939.6799982261379 3.9581662003311264e-120


In [ ]:
fvalue6,pvalue6 = stats.f_oneway(df['Number of vessels fluro'],df['EKG results'])
print(fvalue6, pvalue6)

17.716352995263914 3.0048445245901588e-05


In [ ]:
fvalue7,pvalue7 = stats.f_oneway(df['ST depression'],df['EKG results'])
print(fvalue7, pvalue7)

0.09029342341640771 0.7639205385079485


In [ ]:
fvalue7,pvalue7 = stats.f_oneway(df['Slope of ST'],df['EKG results'])
print(fvalue7, pvalue7)

62.311770603569286 1.6543240534323188e-14


In [ ]:

fvalue8,pvalue8 = stats.f_oneway(df['Max HR'],df['Exercise angina'])
print(fvalue7, pvalue7)

0.09029342341640771 0.7639205385079485


In [ ]:
fvalue9,pvalue9 = stats.f_oneway(df['Thallium'],df['Cholesterol'])
print(fvalue9, pvalue9)


6056.238379441435 6.024205954106358e-295


In [ ]:
fvalue10,pvalue10 = stats.f_oneway(df['Thallium'],df['Exercise angina'])
print(fvalue10, pvalue10)

1290.963175611525 4.559903615428715e-145
